-- 상품 테이블 생성
CREATE TABLE products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '상품 ID',
    product_code VARCHAR(50) NOT NULL UNIQUE COMMENT '상품 코드',
    name VARCHAR(200) NOT NULL COMMENT '상품명',
    price DECIMAL(15, 2) NOT NULL COMMENT '가격',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

    INDEX idx_products_code (product_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='상품';
